MASTER: improve hooks/pre-push

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,13 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 
-protected_branch='master'
-current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
+protected_branches=("master" "develop" "qa" "release")
 
-if [ $current_branch = $protected_branch ]; then
-  echo '[Policy] Cannot push to '$protected_branch' branch. Please push a feature branch and make a PR.'
-  exit 1
+remote=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sed 's#^refs/remotes/##' | cut -d'/' -f1)
+branch=$(git rev-parse --abbrev-ref HEAD)
+
+if [[ " ${protected_branches[@]} " =~ " ${branch} " ]]; then
+    echo "You cannot push changes to the $branch branch. This is a protected branch. Please push your changes to a feature branch and create a pull request instead."
+    exit 1
 fi
 
-unset do_exit
+if [[ "$remote" != "origin" && ! "$remote" =~ ^upstream-.*$ && "$remote" != "$branch" ]]; then
+    echo "You cannot push changes from $branch to $remote."
+    exit 1
+fi
 
 exit 0
